version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_clean
    environment:
      POSTGRES_DB: clean_db
      POSTGRES_USER: clean_user
      POSTGRES_PASSWORD: clean_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
